name: runner-pipeline

on: 
  push:
    branches:
      - main

jobs:
    testing_code:
        runs-on: ubuntu-latest
        steps:
        - name: checkout rpo code
          uses: actions/checkout@v4

        - name: logging to dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: building image
          run: |
           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pf-game:${{ github.sha }} .
        - name: pushing image
          run: |
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/pf-game:${{ github.sha }}
